#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "/root/Documents/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/Documents/android-ndk-r10e/platforms/android-8/arch-arm -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack  -DL_ENDIAN -DTERMIO -O3 -Wall -DMD32_REG_T=int"
  #define PLATFORM "linux-x86_64"
  #define DATE "Thu May 25 00:12:01 PDT 2017"
#endif
